### ISSUE TITLE
Github Action?

### ISSUE THREAD

**Issue by brennobemoura** [finagolfin/swift-android-sdk#111]
Hi there,

Nice job making Android support script. I'm looking forward to use this. 🤘

I'm still in the learning phase, but I would like to ask if is there any chance of converting these scripts into a GitHub Action?

**Comment by finagolfin** [comment]
I suppose you mean making it easy to test your Swift packages for Android by using my SDK to cross-compile on github Actions?

Right now, you'd simply have to copy [what I do in my daily CI, ie download my Android SDK and cross-compile with it](https://github.com/finagolfin/swift-android-sdk/blob/main/.github/workflows/sdks.yml). I doubt I'd ever make that even more automated, say similar to [the Action for setting up an Android emulator that I use in my CI](https://github.com/ReactiveCircus/android-emulator-runner), because it's not that complicated to just download my Android SDK and build with it.

**Comment by brennobemoura** [comment]
Thank you for the explanation. That's exactly what I wanted to know. I will follow your instructions. Congratulations on the job!
