### ISSUE TITLE
Any chance you get do a release for 5.9?

### ISSUE THREAD

**Issue by johnburkey** [finagolfin/swift-android-sdk#117]
Having a hard time running 5.8 builds on latest macOS, and your scripts need to be modernized for 5.9 because of some deprecations in swift.  I did some modernization but then ran into fetching errors ("The file “swift-android-sdktermuxPackages-aarch64” couldn’t be opened because there is no such file)

**Comment by finagolfin** [comment]
Since 5.9 hasn't been released yet, you can only build the source snapshot tags. Those are regularly built and uploaded by my Android CI: [you can download the swift-tests-devel Android SDKs built with the last August 7 5.9 snapshot here](https://github.com/finagolfin/swift-android-sdk/actions/runs/5807022807). My daily Android CI will [start building the just-tagged August 9 5.9 snapshot in 15 mins](https://github.com/finagolfin/swift-android-sdk/actions), and it will be uploaded in a couple hours after being tested with several Swift packages.

It is possible my Swift script in this repo doesn't work with Swift 5.9 but I doubt it. I will check that and let you know.

**Comment by finagolfin** [comment]
I just downloaded the latest 5.9 snapshot toolchain and ran the following command with it to execute the Swift script in this repo, no problem:
```
SWIFT_TAG=swift-5.9-DEVELOPMENT-SNAPSHOT-2023-08-09-a ANDROID_ARCH=aarch64 ../swift-5.9-DEVELOPMENT-SNAPSHOT-2023-08-09-a-ubuntu20.04/usr/bin/swift get-packages-and-swift-source.swift
```
What problem do you see with the latest unmodified version of my Swift script?

**Comment by finagolfin** [comment]
Closing since no response.
